import fs from 'fs';
import Anthropic from '@anthropic-ai/sdk';
import { withRetry } from './retry';

export interface VideoContext {
  title: string;
  description: string;
  audience: string;
  tone: 'enthusiastic' | 'explanatory' | 'friendly' | 'professional' | 'concise' | 'beginner';
  keywords: string;
}

export interface ScriptSegment {
  stepNumber: number;
  text: string;
  videoStartTime: number;
  videoEndTime: number;
}

const MAX_FRAMES = 15;

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

export async function generateScriptFromKeyframes(
  keyframePaths: string[],
  frameTimestamps: number[],
  videoContext: VideoContext,
  videoDuration: number
): Promise<ScriptSegment[]> {
  const indices = subsampleIndices(keyframePaths.length, MAX_FRAMES);
  const frames = indices.map((i) => keyframePaths[i]);
  const sampledTimestamps = indices.map((i) => frameTimestamps[i]);

  console.log(`[script] sending ${frames.length} frames to Claude vision...`);

  const imageContent: Anthropic.ImageBlockParam[] = frames.map((p) => ({
    type: 'image',
    source: {
      type: 'base64',
      media_type: 'image/jpeg',
      data: fs.readFileSync(p).toString('base64'),
    },
  }));

  const textContent: Anthropic.TextBlockParam = {
    type: 'text',
    text: buildPrompt(videoContext, videoDuration, sampledTimestamps, frames.length),
  };

  const response = await withRetry(
    () => client.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 2048,
      messages: [{ role: 'user', content: [...imageContent, textContent] }],
    }),
    { label: 'Claude vision', attempts: 3, baseDelayMs: 1500 }
  );

  const scriptText = (response.content[0] as Anthropic.TextBlock).text;
  console.log(`[script] Claude response received, parsing...`);

  return parseScript(scriptText, sampledTimestamps, videoDuration);
}

function subsampleIndices(total: number, max: number): number[] {
  if (total <= max) return Array.from({ length: total }, (_, i) => i);
  const step = total / max;
  return Array.from({ length: max }, (_, i) => Math.floor(i * step));
}

function buildPrompt(ctx: VideoContext, duration: number, timestamps: number[], frameCount: number): string {
  const targetSteps = Math.max(3, Math.round(duration / 15));
  const frameList = timestamps.map((t, i) => `Screenshot ${i + 1} (${t}s)`).join(', ');
  return `You are writing a voiceover script for a screen recording tutorial. You have ${frameCount} screenshots taken at: ${frameList}.

YOUR ONLY JOB: narrate where the cursor is going and what UI elements are being clicked or filled in. Nothing else.

IGNORE COMPLETELY — do not read, reference, or mention:
- Any text content generated by AI tools (ChatGPT responses, Claude outputs, Gemini answers, Copilot suggestions, etc.)
- Any article, blog post, document, or copy-pasted text visible on screen
- Notifications, popups, or banners unrelated to the tutorial action
- The dock, taskbar, system UI, desktop wallpaper, or background apps
- Any content inside a text editor or AI chat that is not a UI label or field name

ONLY NARRATE:
- The name of the app or website open in the foreground
- Which button, tab, menu, sidebar item, or link the cursor is on or clicks
- Which input field or dropdown is being interacted with, and what is typed into it (only if it is a short form value like a name, email, or setting — not long AI-generated text)
- Which page or screen the user navigated to as a result of a click

TUTORIAL CONTEXT:
- Title: ${ctx.title || 'Screen walkthrough'}
- Description: ${ctx.description || 'Not specified'}
- Audience: ${ctx.audience || 'General'}
- Keywords: ${ctx.keywords || 'none'}
- Total duration: ${Math.round(duration)} seconds

FORMAT:
[STEP 1] We'll start by opening [app or website name].
[STEP 2] Click [exact button/tab/link name] in the [location].
[STEP 3] In the [field name], type [short value if applicable], then click [button name].
...

RULES:
- 1–2 spoken sentences per step, natural and conversational
- Name UI elements exactly as they appear (button label, tab name, menu item)
- Never quote or summarise AI-generated text, blog content, or documents visible on screen
- Use "we'll", "now", "next", "then" to connect steps
- ${ctx.tone === 'enthusiastic' ? 'High energy and exciting — dynamic, punchy language' : ctx.tone === 'explanatory' ? 'Clear and methodical — explain what each action achieves' : ctx.tone === 'friendly' ? 'Warm and casual, like a colleague walking you through it' : ctx.tone === 'professional' ? 'Polished and authoritative — no filler words' : ctx.tone === 'concise' ? 'Ultra-short and direct — strip every unnecessary word' : 'Slow and reassuring — assume the viewer has never done this'}
- First step: introduce what will be accomplished
- Last step: confirm it is done
- Aim for ~${targetSteps} steps

Return ONLY the [STEP N] lines. No intro, no commentary, no markdown.`;
}

function parseScript(scriptText: string, frameTimestamps: number[], totalDuration: number): ScriptSegment[] {
  const stepRegex = /\[STEP\s+(\d+)\]([\s\S]*?)(?=\[STEP\s+\d+\]|$)/gi;
  const segments: ScriptSegment[] = [];
  let match: RegExpExecArray | null;

  while ((match = stepRegex.exec(scriptText)) !== null) {
    const text = match[2].trim();
    if (text) {
      segments.push({ stepNumber: parseInt(match[1], 10), text, videoStartTime: 0, videoEndTime: 0 });
    }
  }

  if (segments.length === 0) {
    return [{ stepNumber: 1, text: scriptText.trim(), videoStartTime: 0, videoEndTime: totalDuration }];
  }

  segments.forEach((seg, i) => {
    const frameIdx = Math.round((i / segments.length) * (frameTimestamps.length - 1));
    const nextFrameIdx = Math.round(((i + 1) / segments.length) * (frameTimestamps.length - 1));
    seg.videoStartTime = frameTimestamps[frameIdx] ?? 0;
    seg.videoEndTime = frameTimestamps[nextFrameIdx] ?? totalDuration;
  });

  segments[segments.length - 1].videoEndTime = totalDuration;

  return segments;
}
